### PR TITLE
Azifh

### PR DESCRIPTION
**Pull request by azifh**
Change Request 1: Add read-only attribute to Quantity input in Issue Purchase Order form
Change Request 2: Implement Vendor ID validity check in Issue Purchase Order form
Change Request 3: Add missing menu navigation to header layout of the Purchasing System website

### CODE REVIEW

**Comment by mridzwan** [comment]
All looks good.

**Comment by azryzdy** [comment]
Approve.

**Comment by itssyem** [comment]
Approve.

**Comment by itssyem** [comment]
Granted.

**Pull request merged**
